### PR TITLE
Release v3.8.48

### PR DESCRIPTION
**Pull request by diegosouzapw**
🚧 Living release notes — cycle opened at v3.8.47 freeze (parallel-cycle model). Synced at each /generate-release phase. DRAFT during the cycle: heavy ci.yml jobs skip drafts (plano mestre testes+CI); flipped ready at the next release's Phase 0a.0a.

### CODE REVIEW

**Comment by ddevsr** [comment]
@diegosouzapw I get this after upgrade to v3.8.47

 v3.8.47

  ⏳ Starting server...


⚠ Server exited (code=1). Restarting in 1s... (1/2)

--- Server crash log ---
node:internal/modules/esm/resolve:271
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module 'D:\Project\laragon\bin\nodejs\node-v24\node_modules\omniroute\dist\head-response-guard.cjs' imported from D:\Project\laragon\bin\nodejs\node-v24\node_modules\omniroute\dist\server-ws.mjs
    at finalizeResolution (node:internal/modules/esm/resolve:271:11)
    at moduleResolve (node:internal/modules/esm/resolve:865:10)
    at defaultResolve (node:internal/modules/esm/resolve:992:11)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:701:20)
    at #resolveAndMaybeBlockOnLoaderThread (node:internal/modules/esm/loader:721:38)
    at ModuleLoader.resolveSync (node:internal/modules/esm/loader:759:56)
    at #resolve (node:internal/modules/esm/loader:683:17)
    at ModuleLoader.getOrCreateModuleJob (node:internal/modules/esm/loader:603:35)
    at ModuleJob.syncLink (node:internal/modules/esm/module_job:163:33)
    at ModuleJob.link (node:internal/modules/esm/module_job:253:17) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///D:/Project/laragon/bin/nodejs/node-v24/node_modules/omniroute/dist/head-response-guard.cjs'
}

Node.js v24.18.0
--- End crash log ---

**Comment by diegosouzapw** [comment]
Superseded: v3.8.48 shipped as a hotfix release via #7055 (merged to main, tag v3.8.48 published). The development cycle continues as release/v3.8.49 — living PR: see the new Release v3.8.49 draft. All 30 open PRs were re-based onto release/v3.8.49.
