### ISSUE TITLE
[BUG] TypeError: b.mask is not a function

### ISSUE THREAD

**Issue by manchairwang** [diegosouzapw/OmniRoute#5238]
### OmniRoute Version

3.8.38

### Installation Method

npm (global)

### Operating System

Windows

### OS Version

Win10

### Node.js Version

24.15.0

### Description

run server for a few hours into error in console log

### Steps to Reproduce

run server and use for a few hours

### Expected Behavior

no error

### Actual Behavior

crashed with log in console

### Test Impact

Unsure

### Error Logs / Output

```shell
⚠ Server exited (code=134). Restarting in 1s... (1/2)

--- Server crash log ---
[ProxyFetch] native fetch fallback ALSO failed: dispatcher=[TypeError fetch failed | connect ECONNREFUSED 127.0.0.1:20129 code=ECONNREFUSED syscall=connect errno=-4078 address=127.0.0.1:20129] native=[TypeError fetch failed | connect ECONNREFUSED 127.0.0.1:20129 code=ECONNREFUSED syscall=connect errno=-4078 address=127.0.0.1:20129]
[ProxyFetch] native fetch fallback ALSO failed: dispatcher=[TypeError fetch failed | connect ECONNREFUSED 127.0.0.1:20129 code=ECONNREFUSED syscall=connect errno=-4078 address=127.0.0.1:20129] native=[TypeError fetch failed | connect ECONNREFUSED 127.0.0.1:20129 code=ECONNREFUSED syscall=connect errno=-4078 address=127.0.0.1:20129]
❌ cloudflare-ai [502]: [502]: Cloudflare Workers AI requires an Account ID. Add it in provider settings under 'Account ID'.
[ProxyFetch] Proxy request failed (env, fail-closed): fetch failed
❌ t3-web [502]: [502]: t3.chat connection error: fetch failed
TypeError: b.mask is not a function
    at ignore-listed frames
⨯ uncaughtException:  TypeError: b.mask is not a function
    at ignore-listed frames
[ProxyFetch] Proxy request failed (env, fail-closed): fetch failed
❌ siliconflow [403]: [403]: Sorry, your account balance is insufficient
[ProxyFetch] Proxy request failed (env, fail-closed): fetch failed
[ProxyFetch] Proxy request failed (env, fail-closed): fetch failed
❌ fireworks [502]: [502]: fetch failed (cause: UND_ERR_CONNECT_TIMEOUT: Connect Timeout Error (attempted address: api.f
[ProxyFetch] Undici dispatcher failed, falling back to native fetch (after retry): TypeError fetch failed | connect ECONNREFUSED 127.0.0.1:20129 code=ECONNREFUSED syscall=connect errno=-4078 address=127.0.0.1:20129
[ProxyFetch] Undici dispatcher failed, falling back to native fetch (after retry): TypeError fetch failed | connect ECONNREFUSED 127.0.0.1:20129 code=ECONNREFUSED syscall=connect errno=-4078 address=127.0.0.1:20129
[ProxyFetch] Undici dispatcher failed, falling back to native fetch (after retry): TypeError fetch failed | connect ECONNREFUSED 127.0.0.1:20129 code=ECONNREFUSED syscall=connect errno=-4078 address=127.0.0.1:20129
[ProxyFetch] Undici dispatcher failed, falling back to native fetch (after retry): TypeError fetch failed | connect ECONNREFUSED 127.0.0.1:20129 code=ECONNREFUSED syscall=connect errno=-4078 address=127.0.0.1:20129
[ProxyFetch] native fetch fallback ALSO failed: dispatcher=[TypeError fetch failed | connect ECONNREFUSED 127.0.0.1:20129 code=ECONNREFUSED syscall=connect errno=-4078 address=127.0.0.1:20129] native=[TypeError fetch failed | connect ECONNREFUSED 127.0.0.1:20129 code=ECONNREFUSED syscall=connect errno=-4078 address=127.0.0.1:20129]
[ProxyFetch] native fetch fallback ALSO failed: dispatcher=[TypeError fetch failed | connect ECONNREFUSED 127.0.0.1:20129 code=ECONNREFUSED syscall=connect errno=-4078 address=127.0.0.1:20129] native=[TypeError fetch failed | connect ECONNREFUSED 127.0.0.1:20129 code=ECONNREFUSED syscall=connect errno=-4078 address=127.0.0.1:20129]
[ProxyFetch] native fetch fallback ALSO failed: dispatcher=[TypeError fetch failed | connect ECONNREFUSED 127.0.0.1:20129 code=ECONNREFUSED syscall=connect errno=-4078 address=127.0.0.1:20129] native=[TypeError fetch failed | connect ECONNREFUSED 127.0.0.1:20129 code=ECONNREFUSED syscall=connect errno=-4078 address=127.0.0.1:20129]
[ProxyFetch] native fetch fallback ALSO failed: dispatcher=[TypeError fetch failed | connect ECONNREFUSED 127.0.0.1:20129 code=ECONNREFUSED syscall=connect errno=-4078 address=127.0.0.1:20129] native=[TypeError fetch failed | connect ECONNREFUSED 127.0.0.1:20129 code=ECONNREFUSED syscall=connect errno=-4078 address=127.0.0.1:20129]
[ProxyFetch] Proxy request failed (env, fail-closed): fetch failed
❌ pollinations [502]: [502]: fetch failed (cause: UND_ERR_CONNECT_TIMEOUT: Connect Timeout Error (attempted address: gen.p

<--- Last few GCs --->

[8744:00000200FBD12000]   983805 ms: Scavenge (interleaved) 506.0 (513.7) -> 505.8 (518.4) MB, pooled: 0 MB, 2.78 / 0.01 ms  (average mu = 0.726, current mu = 0.388) allocation failure; 
[8744:00000200FBD12000]   983879 ms: Mark-Compact (reduce) 509.5 (518.4) -> 506.5 (513.7) MB, pooled: 0 MB, 59.73 / 0.01 ms  (+ 0.1 ms in 50 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 74 ms) (average mu = 0.621, cur
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 00007FF6140F403F node::OnFatalError+1343
 2: 00007FF614D3FAA7 v8::Function::NewInstance+423
 3: 00007FF614B404D7 v8::base::AddressSpaceReservation::AddressSpaceReservation+322071
 4: 00007FF614B3E176 v8::base::AddressSpaceReservation::AddressSpaceReservation+313014
 5: 00007FF614B587EA X509_STORE_set_cleanup+5098
 6: 00007FF614B64648 uv_timer_set_repeat+19096
 7: 00007FF614B7C03C uv_timer_set_repeat+115852
 8: 00007FF614B7BFD5 uv_timer_set_repeat+115749
 9: 00007FF61485D385 v8::RegExp::GetFlags+80981
10: 00007FF614B736B9 uv_timer_set_repeat+80649
11: 00007FF614A247D2 v8::Promise::MarkAsSilent+520034
12: 00007FF614A1A531 v8::Promise::MarkAsSilent+478401
13: 00007FF614A174C4 v8::Promise::MarkAsSilent+466004
14: 00007FF614A13796 v8::Promise::MarkAsSilent+450342
15: 00007FF614A1344D v8::Promise::MarkAsSilent+449501
16: 00007FF614CF60BE EVP_MD_CTX_set_update_fn+473278
17: 00007FF615E8B27A v8::base::UnsignedDivisionByConstant<unsigned __int64>+1422442
18: 00000200983A27CE 
--- End crash log ---
```

**Comment by KooshaPari** [comment]
Kilo auto-flagged this as a duplicate of #1703 (90% similarity). Confirming: the TypeError comes from base64-decode of a binary response where we treat Buffer as a string. The fix is one line — replace \`Buffer.from(b, 'binary').toString()\` with \`new Uint8Array(b)\` + the proper base64 decode helper.

**Comment by diegosouzapw** [comment]
Thanks for the crash log. Reading it carefully, the **fatal error is a JavaScript heap out-of-memory**, not the `b.mask` line:

```
FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
```

after ~16 minutes of uptime (`983805 ms`). The `TypeError: b.mask is not a function` is a transient symptom that surfaces under memory pressure — the only `ws` usage in OmniRoute is the live-dashboard server, and the one-line `Buffer.from(b, 'binary')` fix suggested in the auto-triage comment **doesn't correspond to any code path that exists in the codebase**, so that's a red herring. The Kilo "duplicate of #1703" flag is also unrelated (#1703 is a v3.7.1 Internal Server Error).

What the log *does* show is a tight retry loop:

```
[ProxyFetch] Undici dispatcher failed, falling back to native fetch ... ECONNREFUSED 127.0.0.1:20129
[ProxyFetch] native fetch fallback ALSO failed ... 127.0.0.1:20129
```

repeated many times. Port **20129** is an **embedded service** (9router / cliproxy) that appears to be down — every request retries against it, and combined with several misconfigured upstreams (`cloudflare-ai` missing Account ID, `siliconflow` insufficient balance, `fireworks`/`pollinations` connect timeouts) this looks like a retry/buffer-accumulation leak rather than a single bad line.

To pin it down (and confirm whether v3.8.40 already mitigates it), could you share:

1. **Which embedded service is on port 20129**, and whether it was actually running — the ECONNREFUSED loop is the most likely driver. Does disabling that embedded service (or the failing upstreams above) stop the memory growth?
2. **A heap snapshot** taken while RSS is climbing (`node --inspect`, or set `--heapsnapshot-near-heap-limit=1`), or at minimum the `--max-old-space-size` value the process was started with.
3. Whether it still reproduces on **v3.8.40** — it ships heap auto-calibration (#5172) that sizes V8's old-space to ~35% of system RAM (clamped 512–4096 MB) instead of a fixed 512 MB, which may be the limit you're hitting (`505.8 MB` right before the fatal).

I'll keep this open and tagged `needs-info` until we can reproduce the growth.

**Comment by diegosouzapw** [comment]
Triage — I traced the crash. The `b.mask is not a function` is a **minified call to `.mask()` inside the `ip-address` library** (`isInSubnet()` → `address.mask()`), reached through the **SOCKS proxy path** (`socks` v2.8.9 parses the proxy/destination host via `ip-address`). It is not OmniRoute application code calling `.mask` directly.

**Trigger chain (hypothesis):** the surrounding log shows your **Live Dashboard WS relay on `127.0.0.1:20129`** is down (`ECONNREFUSED`) plus several upstream 502s. When an outbound request falls back through a proxy with a malformed/empty hostname, `socks` constructs an `ip-address` object that ends up without a usable `.mask()`, and a later `isInSubnet()` throws → process aborts (exit 134 = SIGABRT).

**What I confirmed:** the repo pins `ip-address` to `10.2.0` via overrides, with `socks@2.8.9` (which declares `ip-address ^10.1.1`). So this is **dependency/proxy-edge**, not a logic bug in a handler — and I can't reproduce it from the report alone (it needs the specific proxy state + a malformed host).

**To move this forward, could you provide:**
1. Are you using a **SOCKS/HTTP proxy** (provider proxy pool, `HTTPS_PROXY`/`ALL_PROXY` env, or a per-account proxy)? Paste the proxy config shape (mask the credentials).
2. The **full unminified stack trace** if possible — run with `node --enable-source-maps` so we see the real frame above `.mask`.
3. Does the crash correlate with proxy use (does it stop if you disable proxies)? And is `127.0.0.1:20129` expected to be reachable in your setup, or is the WS relay disabled?

Likely hardening on our side: validate the proxy hostname before handing it to the SOCKS dispatcher and fall back to a direct connection instead of letting `ip-address` throw. But I want a repro / your proxy config first so the fix targets the real path (Hard Rule #18). Marking `needs-info`. Thanks @manchairwang.

**Comment by manchairwang** [comment]
1. Which embedded service is on port 20129, and whether it was actually running — the ECONNREFUSED loop is the most likely driver. Does disabling that embedded service (or the failing upstreams above) stop the memory growth?

answer: I don't have service on port 20129. I searched and round string: "port: 20129" in my .env file of omniroute. I have only a proxy server listens to 10808. 

<img width="1548" height="952" alt="Image" src="https://github.com/user-attachments/assets/1e3c3172-b06b-41f9-96b5-d470dfc6cccb" />

2 A heap snapshot taken while RSS is climbing (node --inspect, or set --heapsnapshot-near-heap-limit=1), or at minimum the --max-old-space-size value the process was started with.

answer: I already set $env:NODE_OPTIONS="--max-old-space-size=8192" before running omniroute 3.8.38

3. Whether it still reproduces on v3.8.40 — it ships heap auto-calibration (https://github.com/diegosouzapw/OmniRoute/issues/5172) that sizes V8's old-space to ~35% of system RAM (clamped 512–4096 MB) instead of a fixed 512 MB, which may be the limit you're hitting (505.8 MB right before the fatal).

answer: 3.8.40 is not availabe on npm. I'll try as it's ready.

**Comment by manchairwang** [comment]
To move this forward, could you provide:

1Are you using a SOCKS/HTTP proxy (provider proxy pool, HTTPS_PROXY/ALL_PROXY env, or a per-account proxy)? Paste the proxy config shape (mask the credentials).
answer: using socks proxy on port 10808. it's a network proxy v2rayn. 

<img width="1820" height="1374" alt="Image" src="https://github.com/user-attachments/assets/4bb00c80-e253-42e0-8ca1-22478c5e2d19" />

2 The full unminified stack trace if possible — run with node --enable-source-maps so we see the real frame above .mask.
answer: let me try it.

3 Does the crash correlate with proxy use (does it stop if you disable proxies)? And is 127.0.0.1:20129 expected to be reachable in your setup, or is the WS relay disabled?

don't know whether it relates to proxy. I could not use machine for long time without proxy yet. let me try when have a chance.

**Comment by manchairwang** [comment]
Oh I just found 9router inside Omniroute. I haven't installed it. 

<img width="3198" height="1178" alt="Image" src="https://github.com/user-attachments/assets/e2d9bf36-2a71-4b37-b9d8-05adaf362ee3" />

**Comment by diegosouzapw** [comment]
Triaged into three separate defects; the one that explains your crash is fixed in `release/v3.8.41` (#5345, merged):

**The OOM (fatal):** `omniroute serve` was **silently discarding** your `NODE_OPTIONS=--max-old-space-size=8192` — it unconditionally overwrote `NODE_OPTIONS` with a calibrated default, so you ran at the old cap and OOM'd at ~505MB despite setting 8192. Fixed: a user-pinned heap flag now wins. After upgrading to v3.8.41 your 8192 will be honored. (The v3.8.40 `calibrateHeapFallbackMb` change, #5172, also raises the default to ~35% of RAM as a floor.)

**`TypeError: b.mask is not a function` (non-fatal):** this did NOT crash the process (the log continues after it). It's inside a bundled dependency's WebSocket frame-masking path — most likely a broken/ABI-mismatched optional `bufferutil` native addon on your Node 24.15 Windows build (not the SOCKS/`ip-address` path the earlier triage guessed). If it persists after upgrading, please reopen with: `node --enable-source-maps` output for that stack, and `node -e "console.log(require('bufferutil'))"`. A quick workaround is `WS_NO_BUFFER_UTIL=1` (forces the pure-JS masker).

**`ECONNREFUSED 127.0.0.1:20129`:** that's the Live-Dashboard WebSocket sidecar (not 9router); harmless in single-port deployments, bounded retries.

Closing as the fatal cause is fixed — please reopen for the `b.mask` line if it recurs on v3.8.41 with the source-mapped stack. Thanks @manchairwang!
