### ISSUE TITLE
[BUG] Broken JSX merge in EndpointPageClient.tsx breaks dashboard typecheck/lint (from #11228)

### ISSUE THREAD

**Issue by maxmad64bis** [diegosouzapw/OmniRoute#11253]
### OmniRoute Version

3.8.50 (`release/v3.8.50`)

### Installation Method

Built from source

### Operating System

Linux — not OS-specific; this is a static JSX parse error caught by `tsc`/ESLint, reproducible on any OS.

## Description

`release/v3.8.50`'s dashboard fails its own TypeScript typecheck gate because of a broken JSX merge in the Endpoint page: the return statement of an inner helper (rendering each model row inside `ProviderModelsModal`) got overwritten mid-function by an unrelated block of page-header JSX, instead of that header landing on the outer component's own return. The two `return (...)` blocks are now interleaved, which breaks parsing for the rest of the file.

Introduced in #11228 (merged 2026-08-23), unrelated to any provider/routing change — pure JSX placement mistake.

## Steps to Reproduce

1. Check out `release/v3.8.50`.
2. Run `npm run check:dashboard-typecheck` (or `npx tsc --noEmit -p tsconfig.typecheck-dashboard.json`).

## Expected Behavior

The dashboard typecheck gate passes for this file (as it does for every other file under `src/app/(dashboard)/`).

## Actual Behavior

TypeScript fails to parse the file from line 2355 onward:

```
src/app/(dashboard)/dashboard/endpoint/EndpointPageClient.tsx(2355,8): error TS17008: JSX element 'div' has no corresponding closing tag.
src/app/(dashboard)/dashboard/endpoint/EndpointPageClient.tsx(2397,11): error TS1381: Unexpected token. Did you mean `{'}'}` or `&rbrace;`?
... (cascades into ~15 more parser errors through the rest of the file)
```

Root cause, from `git show 8a42aeebb -- src/app/\(dashboard\)/dashboard/endpoint/EndpointPageClient.tsx`:

```diff
         <div className="flex flex-col gap-1">
           {groupModels.map((m) => {
             const copyKey = `modal-${m.id}`;
-            return (
+  return (
+    <div className="flex flex-col gap-4">
+      <h1 className="text-2xl font-bold">{t("endpoint.title")}</h1>
+      ...page header JSX...
               <div
                 key={m.id}
                 className="flex items-center gap-2 px-3 py-2 rounded-lg hover:bg-surface/60 group"
```

The new page-header block replaced the inner `.map()` callback's `return (`, instead of being inserted at the outer component's own return further down the file. `npm run lint` also fails to parse the file for the same reason.

## Test Impact

Existing automated test already fails — `check:dashboard-typecheck` (this gate is exactly what should have caught it before merge; the frozen baseline (`quality-baseline.json`) doesn't cover this file's new-error count yet).

## Additional Context

Likely one of the concrete causes behind the open "Release branch not green: release/v3.8.50" tracker (#9985).

## Validation Plan

- `npm run check:dashboard-typecheck` passes with 0 new/regressed errors for `EndpointPageClient.tsx`
- `npm run lint` parses the file without error

**Comment by diegosouzapw** [comment]
Confirmed and already fixed — this is exactly the defect we root-caused this morning: the squash merge of #11228 applied its endpoint-header hunk inside `ProviderModelsModal`, overwriting the `groupModels.map` callback's `return (`. Fix landed in **#11256** (merged 16:17 UTC): surgical revert of that single hunk, file byte-identical to its pre-#11228 state, Fast Production Build green again, and the pre-existing jsdom render suite (which imports the component) back to 4/4 as the permanent regression guard. The guided header itself will be re-proposed against the page-level component in a follow-up. Thanks for the precise report — you nailed the mechanism (and the culprit PR) in one paragraph.
